### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mat4444**

### CODE REVIEW

**Comment by rytilahti** [comment]
Hi Mat and thanks for the PR! I presume you are still making some changes, considering you left the PR as draft?

One suggestion, maybe keep the manual setup (i.e., copying the file over) and rename the section you are now working on as "HASS.io" installation. Otherwise it's looking good :-)

**Comment by mat4444** [comment]
Hi! 
I have updated the procedure as follows:
- Installation of your Python library for Home Assistant (the full packaged software that can be installed directly on a Raspberry Pi). (BTW, "Home Assistant" is the new name for "Hass.io" since January, when they changed their branding). 
- Custom component installation (the file copy part), that is required whatever your installation is (Home Assistant or Home Assistant Core).
Let me know what you think

**Comment by rytilahti** [comment]
Looks good to me, thanks :+1:

**Comment by mat4444** [comment]
Thank you ! Hope it will help other users

**Pull request merged**
